// Auto-generated by scripts/generate-routes.mjs
// Source: execution-plan/raw-mirror/www.southwestplanningconsultancy.co.uk/services/rural-planning-development.html
// URL: /services/rural-planning-development
import { readFile } from 'node:fs/promises';
import DOMPurify from 'isomorphic-dompurify';
import { buildHeadFromHtml, extractBodyInner } from '../../../_lib/page';

const SOURCE = 'execution-plan/raw-mirror/www.southwestplanningconsultancy.co.uk/services/rural-planning-development.html';
const PAGE_URL = '/services/rural-planning-development';

export const dynamic = 'force-static';
export const revalidate = false;

export async function generateMetadata() {
  try {
    const raw = await readFile(SOURCE, 'utf-8');
    return buildHeadFromHtml(raw, PAGE_URL);
  } catch {
    return {};
  }
}

export default async function Page() {
  let body = '';
  try {
    const raw = await readFile(SOURCE, 'utf-8');
    body = extractBodyInner(raw, PAGE_URL);
  } catch (e) {
    body = '<p>Failed to load mirrored content.</p>';
  }
  const clean = DOMPurify.sanitize(body, {
    USE_PROFILES: { html: true },
    ADD_ATTR: ['target', 'rel', 'loading'],
  });
  return <div dangerouslySetInnerHTML={{ __html: clean }} />;
}
