#!/usr/bin/env node
/**
 * generate-routes.mjs
 * Reads execution-plan/site-map.md and emits one app/(routes)/<slug>/page.tsx
 * per discovered URL. Each page renders the original HTML via DOMPurify-sanitized
 * dangerouslySetInnerHTML — pixel parity on day one, structured extraction
 * possible later when Payload takes over.
 *
 * Run: node scripts/generate-routes.mjs
 */

import { readFile, writeFile, mkdir, readdir, stat } from "node:fs/promises";
import { existsSync } from "node:fs";
import { resolve, join, relative, dirname, sep } from "node:path";

const ROOT = resolve(process.cwd());
const SITE_MAP = join(ROOT, "execution-plan", "site-map.md");
const MIRROR = join(
	ROOT,
	"execution-plan",
	"raw-mirror",
	"www.southwestplanningconsultancy.co.uk",
);
const APP = join(ROOT, "app");
const ROUTES = join(APP, "(routes)");

if (!existsSync(SITE_MAP)) {
	console.error("site-map.md not found. Run `npm run extract` first.");
	process.exit(1);
}
if (!existsSync(MIRROR)) {
	console.error("raw-mirror/ not found. Run wget first.");
	process.exit(1);
}

const siteMap = await readFile(SITE_MAP, "utf-8");
const rows = [];
for (const line of siteMap.split("\n")) {
	const m = line.match(/^\| `([^`]+)` \| `([^`]+)` \|/);
	if (m) rows.push({ url: m[1], file: m[2] });
}

console.log(`Discovered ${rows.length} pages in site-map.md`);

await mkdir(ROUTES, { recursive: true });

let created = 0;
for (const { url, file } of rows) {
	if (url === "/") continue; // handled by app/page.tsx

	const slug = url.replace(/^\//, "").replace(/\/$/, "");
	if (!slug) continue;

	// Build a folder path that mirrors the URL structure.
	// /about-us            → app/(routes)/about-us/page.tsx
	// /services/foo        → app/(routes)/services/foo/page.tsx
	const parts = slug.split("/").filter(Boolean);
	const routeDir = join(ROUTES, ...parts);
	await mkdir(routeDir, { recursive: true });
	const pagePath = join(routeDir, "page.tsx");

	const mirrorFile = join(MIRROR, file);
	const relMirror = relative(ROOT, mirrorFile).replace(/\\/g, "/");

	// The page is at app/(routes)/<parts...>/page.tsx and _lib is at app/_lib/page.ts.
	// Depth from page file to app/ is len(parts) + 1 (the (routes) folder).
	const depth = parts.length + 1; // (routes) + parts
	const libImport = "../".repeat(depth) + "_lib/page";

	const content = `// Auto-generated by scripts/generate-routes.mjs
// Source: ${relMirror}
// URL: ${url}
import { readFile } from 'node:fs/promises';
import DOMPurify from 'isomorphic-dompurify';
import { buildHeadFromHtml, extractBodyInner } from '${libImport}';
import { getPageSeo } from '${libImport.replace(/_lib\/page$/, '_lib/seo')}';

const SOURCE = '${relMirror}';
const PAGE_URL = '${url}';

export const dynamic = 'force-static';
export const revalidate = false;

export async function generateMetadata() {
  const seo = getPageSeo(PAGE_URL);
  try {
    const raw = await readFile(SOURCE, 'utf-8');
    return buildHeadFromHtml(raw, PAGE_URL, seo);
  } catch {
    return {
      title: seo.title,
      description: seo.description,
    };
  }
}

export default async function Page() {
  let body = '';
  try {
    const raw = await readFile(SOURCE, 'utf-8');
    body = extractBodyInner(raw, PAGE_URL);
  } catch (e) {
    body = '<p>Failed to load mirrored content.</p>';
  }
  const clean = DOMPurify.sanitize(body, {
    USE_PROFILES: { html: true },
    ADD_ATTR: ['target', 'rel', 'loading'],
  });
  return <div dangerouslySetInnerHTML={{ __html: clean }} />;
}
`;
	await writeFile(pagePath, content);
	created++;
}

// Always create a homepage app/page.tsx
const homeRow = rows.find((r) => r.url === "/");
if (homeRow) {
	const homeContent = `// Auto-generated by scripts/generate-routes.mjs
// Source: execution-plan/raw-mirror/www.southwestplanningconsultancy.co.uk/${homeRow.file}
// URL: /
import { readFile } from 'node:fs/promises';
import DOMPurify from 'isomorphic-dompurify';
import { buildHeadFromHtml, extractBodyInner } from './_lib/page';
import { getPageSeo } from './_lib/seo';

const SOURCE = 'execution-plan/raw-mirror/www.southwestplanningconsultancy.co.uk/${homeRow.file}';
const PAGE_URL = '/';

export const dynamic = 'force-static';
export const revalidate = false;

export async function generateMetadata() {
  const seo = getPageSeo(PAGE_URL);
  try {
    const raw = await readFile(SOURCE, 'utf-8');
    return buildHeadFromHtml(raw, PAGE_URL, seo);
  } catch {
    return {
      title: seo.title,
      description: seo.description,
    };
  }
}

export default async function HomePage() {
  let body = '';
  try {
    const raw = await readFile(SOURCE, 'utf-8');
    body = extractBodyInner(raw, PAGE_URL);
  } catch (e) {
    body = '<p>Failed to load mirrored content.</p>';
  }
  const clean = DOMPurify.sanitize(body, {
    USE_PROFILES: { html: true },
    ADD_ATTR: ['target', 'rel', 'loading'],
  });
  return <div dangerouslySetInnerHTML={{ __html: clean }} />;
}
`;
	await writeFile(join(APP, "page.tsx"), homeContent);
	console.log("Wrote app/page.tsx (home)");
}

console.log(`Wrote ${created} route files in app/(routes)/`);
