// @ts-nocheck
// This file is auto-generated by Payload. It maps admin components (custom
// field UI, custom views) to their source paths. For v1 we have no custom
// components, so this is a minimal empty map.
export const importMap = {};
