/**
 * Public types used by the public-side wiring. Mirrors the Payload
 * collection shapes; if `src/payload-types.ts` exists (generated by
 * `payload generate:types`), prefer importing from there for accuracy.
 */
export type Media = {
	id: string | number;
	filename?: string;
	url?: string;
	alt?: string;
	mimeType?: string;
	filesize?: number;
	width?: number;
	height?: number;
};

export type Service = {
	id: string | number;
	slug: string;
	name: string;
	subtitle?: string;
	displayOrder?: number;
	cardImage?: Media | string;
	description?: string;
	longDescription?: unknown;
	contactFormEnabled?: boolean;
};

export type Page = {
	id: string | number;
	slug: string;
	title: string;
	metaTitle?: string;
	metaDescription?: string;
	ogImage?: Media | string;
	showInNav?: boolean;
	body?: Array<{
		zoneId: string;
		block: { blockType: string; [k: string]: unknown };
	}>;
	updatedAt?: string;
};

export type SiteSettingsData = {
	logo?: Media | string;
	companyName?: string;
	companyTagline?: string;
	address?: string;
	registeredOffice?: string;
	phoneNumbers?: Array<{ value: string }>;
	email?: string;
	registrationNumber?: string;
	socialLinks?: {
		instagram?: string;
		twitter?: string;
		linkedin?: string;
		facebook?: string;
	};
	footerText?: string;
};
